import React, { useState } from 'react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { dracula } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { Copy, Check, CodeIcon, AlertTriangle } from 'lucide-react';

/**
 * Component to display the auto-refactored code generated by the LLM,
 * including a copy-to-clipboard option.
 */
const UpdatedCode = ({ code, refactoringSuccessful }) => {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        if (code) {
            navigator.clipboard.writeText(code.trim());
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    // Only show error if code is truly empty or null
    if (!code || code.trim().length === 0) {
        return (
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                <div className="flex items-center space-x-2 text-gray-500">
                    <AlertTriangle size={20} />
                    <p>No code available for this file.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="updated-code-section space-y-4">
            {/* Header with Copy Button */}
            <div className="flex justify-between items-center">
                <h2 className="text-xl font-bold text-gray-900 flex items-center space-x-2">
                    <CodeIcon size={24} className="text-sky-600" />
                    <span>Auto-refactored Code</span>
                    {refactoringSuccessful === false && (
                        <span className="text-sm font-normal text-amber-600 ml-2">
                            (Original - Refactoring Failed)
                        </span>
                    )}
                </h2>

                {/* Copy Button */}
                <button
                    onClick={handleCopy}
                    className={`
                        flex items-center space-x-2 px-4 py-2 text-sm font-medium rounded-lg 
                        transition duration-200 shadow-sm
                        ${copied 
                            ? 'bg-green-600 text-white hover:bg-green-700' 
                            : 'bg-gray-700 text-gray-200 hover:bg-gray-600'
                        }
                    `}
                    aria-label="Copy code to clipboard"
                >
                    {copied ? (
                        <>
                            <Check size={16} />
                            <span>Copied!</span>
                        </>
                    ) : (
                        <>
                            <Copy size={16} />
                            <span>Copy Code</span>
                        </>
                    )}
                </button>
            </div>

            {/* Warning Banner if refactoring failed */}
            {refactoringSuccessful === false && (
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 flex items-start space-x-3">
                    <AlertTriangle size={20} className="text-amber-600 flex-shrink-0 mt-0.5" />
                    <div>
                        <p className="text-sm font-medium text-amber-900">
                            Auto-refactoring was not successful
                        </p>
                        <p className="text-sm text-amber-700 mt-1">
                            The LLM could not generate valid refactored code. Showing the original code instead.
                        </p>
                    </div>
                </div>
            )}

            {/* Code Display */}
            <div className="rounded-lg overflow-hidden border border-gray-200">
                <SyntaxHighlighter 
                    language="python" 
                    style={dracula} 
                    customStyle={{ 
                        borderRadius: '8px', 
                        padding: '1.5rem',
                        fontSize: '0.875rem',
                        lineHeight: '1.5',
                        margin: 0,
                    }}
                    showLineNumbers={true}
                >
                    {code.trim()}
                </SyntaxHighlighter>
            </div>
        </div>
    );
};

export default UpdatedCode;
